NUMPY-(Numerical PYTHON)
-
It is the Library of "PYTHON".
Linear Algebra - Library. 
Intel MKL OR "OPENBLAS".

Store same type of Data - Homogeneous 
Store data very compacaly- Fast 
Consume Less memory - Less Memory

In [3]:
import numpy as np
 # np is alias of numpy in python

Creating list in python

In [4]:
l=list = [1,2,3,4,5]
print(l)


[1, 2, 3, 4, 5]


In [5]:
l #l is list here


[1, 2, 3, 4, 5]

Creating Array in numpy

We have to deal in Arrays in numpy

In [6]:
#creating 1-d array
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [7]:
#creating 2-d array
#2-d : passing 2 - list within the list 
ar = np.array([[1,2],[3,4]])
ar

array([[1, 2],
       [3, 4]])

In [8]:
# converting list to array
type(np.array(l)) #altarnative



numpy.ndarray

In [9]:
ar.ndim # describes the nature of array

2

In [10]:
ar.itemsize # describe about the size the numbers

4

In [11]:
ar.dtype # describe about the nature of data type

dtype('int32')

In [12]:
ar.shape

(2, 2)

In [13]:
# list to array
b=np.matrix(l) #convert array to matrix

In [14]:
b   #b stores matrix

matrix([[1, 2, 3, 4, 5]])

What we studied so far...!
-
What is list?

Python List vs Numpy list!

What i array, Numpy Array,1-d array, 2-d array, Array to 2-d array!

Converting List to Array

Converting List to Matrix

List of list
-
You are given a soduko list, sudoku_list is a Python list containing a sudoku game.

In [15]:
#list with in the list
sudoku_list= [[0, 0, 4, 3, 0], [0, 0, 5, 0, 0], [0, 7, 0, 0, 6],[0,0,9,0,0],[0,0,3,6,0]]
print(sudoku_list)  #list
sudoku_list         #array

[[0, 0, 4, 3, 0], [0, 0, 5, 0, 0], [0, 7, 0, 0, 6], [0, 0, 9, 0, 0], [0, 0, 3, 6, 0]]


[[0, 0, 4, 3, 0],
 [0, 0, 5, 0, 0],
 [0, 7, 0, 0, 6],
 [0, 0, 9, 0, 0],
 [0, 0, 3, 6, 0]]

 Change sudoku_list into a NumPy array and give the type of new soduko_list:


In [16]:
u=np.array([[0, 0, 4, 3, 0], [0, 0, 5, 0, 0]])
i=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(u.shape)
print(i.shape)
print(u) 
#matrix
i
#array


(2, 5)
(2, 5)
[[0 0 4 3 0]
 [0 0 5 0 0]]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [17]:
u.dtype


dtype('int32')

In [18]:
i.dtype

dtype('int32')

Initialization of arrays
-

In [19]:
zeros = np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
ones = np.ones((3,3))
ones


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
full=np.full((3,3),7)
full

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [22]:
identity = np.identity((3))
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.ones(6).dtype

dtype('float64')

In [24]:
array10 = np.array([[1,2.0,3],[4,5,6.9]],dtype ='int32')
array10

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
array10.dtype

dtype('int32')

Basic Function
-

In [26]:
w=u-i
w


array([[ -1,  -2,   1,  -1,  -5],
       [ -6,  -7,  -3,  -9, -10]])

In [27]:
e=u+i
e


array([[ 1,  2,  7,  7,  5],
       [ 6,  7, 13,  9, 10]])

In [28]:
v=e*i
v

array([[  1,   4,  21,  28,  25],
       [ 36,  49, 104,  81, 100]])

In [29]:
y=e/i
y

array([[1.        , 1.        , 2.33333333, 1.75      , 1.        ],
       [1.        , 1.        , 1.625     , 1.        , 1.        ]])

In [30]:
g=i*i
g

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]])

In [31]:
t=i**i
t

array([[         1,          4,         27,        256,       3125],
       [     46656,     823543,   16777216,  387420489, 1410065408]])

Slicing
-


In [32]:
array2 = np.array([3,4,5,6,87,8])
arr = array2[2:4]

In [33]:
arr 

array([5, 6])

In [34]:
arr[0]=99
array2

array([ 3,  4, 99,  6, 87,  8])