NUMPY-(Numerical PYTHON)
-
It is the Library of "PYTHON".
Linear Algebra - Library. 
Intel MKL OR "OPENBLAS".

Store same type of Data - Homogeneous 
Store data very compacaly- Fast 
Consume Less memory - Less Memory

In [1]:
import numpy as np
 # np is alias of numpy in python

Creating list in python

In [45]:
l=list = [1,2,3,4,5]
print(l)


[1, 2, 3, 4, 5]


In [46]:
l #l is list here


[1, 2, 3, 4, 5]

Creating Array in numpy

We have to deal in Arrays in numpy

In [56]:
#creating 1-d array
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [68]:
#creating 2-d array
#2-d : passing 2 - list within the list 
ar = np.array([[1,2],[3,4]])
ar

array([[1, 2],
       [3, 4]])

In [71]:
# converting list to array
type(np.array(l)) #altarnative



numpy.ndarray

In [72]:
ar.ndim # describes the nature of array

2

In [73]:
ar.itemsize # describe about the size the numbers

4

In [74]:
ar.dtype # describe about the nature of data type

dtype('int32')

In [75]:
ar.shape

(2, 2)

In [54]:
# list to array
b=np.matrix(l)

In [52]:
b   #b stores matrix

matrix([[1, 2, 3, 4, 5]])

What we studied so far...!
-
What is list?

Python List vs Numpy list!

What i array, Numpy Array,1-d array, 2-d array, Array to 2-d array!

Converting List to Array

Converting List to Matrix

List of list
-
You are given a soduko list, sudoku_list is a Python list containing a sudoku game.

In [40]:
#list with in the list
sudoku_list= [[0, 0, 4, 3, 0], [0, 0, 5, 0, 0], [0, 7, 0, 0, 6],[0,0,9,0,0],[0,0,3,6,0]]
print(sudoku_list)  #list
sudoku_list         #array

[[0, 0, 4, 3, 0], [0, 0, 5, 0, 0], [0, 7, 0, 0, 6], [0, 0, 9, 0, 0], [0, 0, 3, 6, 0]]


[[0, 0, 4, 3, 0],
 [0, 0, 5, 0, 0],
 [0, 7, 0, 0, 6],
 [0, 0, 9, 0, 0],
 [0, 0, 3, 6, 0]]

 Change sudoku_list into a NumPy array and give the type of new soduko_list:


In [ ]:
a=np.array([[0, 0, 4, 3, 0, 0, 2, 0, 9], [0, 0, 5, 0, 0, 9, 0, 0, 1]])
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a.shape)
print(b.shape)
print(a) 
print(b)
#matrix
a  #array


In [ ]:
a.dtype


In [ ]:
b.dtype

Initialization of arrays
-

In [24]:
zeros = np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
ones = np.ones((3,3))
ones


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
full=np.full((3,3),7)
full

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [22]:
identity = np.identity((3))
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])